---
version: '3'

vars:
  CC: gcc
  CC_FLAGS: "-Werror -Wextra -Wall -Wfree-nonheap-object -std=c17"
  LAB_EXECUTABLE_NAME: lab
  SOURCE_FILES:
    - util.c
    - env.c
    - explode.c
    - regex.c
  DYLIB_NAME: libstandardloop-util.dylib
  DYLIB_PATH: /usr/local/lib/standardloop/
  DYLIB_INCLUDE_PATH: /usr/local/include/standardloop/
  RELEASE_VERSION: 0.0.5

tasks:
  default:
    deps:
      - lab

  check-version:
    silent: true
    cmds:
      - cat util.h | grep -q {{.RELEASE_VERSION}}
      - cat util.h | grep -q "MAJOR_VERSION 0"
      - cat util.h | grep -q "MINOR_VERSION 0"
      - cat util.h | grep -q "PATCH_VERSION 5"

  release:
    deps:
      - check-version
      - release:build
      - release:move-files

  release:build:
    run: once
    deps:
      - check-version
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        -O3 \
        -dynamiclib \
        -current_version {{.RELEASE_VERSION}} \
        -compatibility_version {{.RELEASE_VERSION}} \
        -o {{.DYLIB_NAME}}
    sources:
      - "*.c"
    generates:
      - "{{.DYLIB_NAME}}"
  
  release:move-files:
    deps:
      - release:build
    cmds:
      - sudo -v
      - sudo mv {{.DYLIB_NAME}} {{.DYLIB_PATH}}
      - sudo cp util.h {{.DYLIB_INCLUDE_PATH}}

  release:clean:
    allow_failure: true
    cmds:
      - sudo -v
      - sudo rm -f {{.DYLIB_PATH}}/{{.DYLIB_NAME}}
      - sudo rm -f {{.DYLIB_INCLUDE_PATH}}/util.h
    
  # local test
  remote:download:
    run: once
    cmds:
      - |
        mkdir -p tmp
        cd tmp
        curl -O -J -L https://github.com/standardloop/c-util/releases/download/v{{.RELEASE_VERSION}}/libstandardloop-util.zip
        unzip libstandardloop-util.zip
        rm libstandardloop-util.zip

  remote:move:
    deps:
      - remote:download
    cmds:
      - |
        cd tmp/
        sudo -v
        sudo mv {{.DYLIB_NAME}} {{.DYLIB_PATH}}
        sudo mv util.h {{.DYLIB_INCLUDE_PATH}}

  lab:
    deps:
      - lab:run

  lab:build:
    run: once
    cmds:
      - |
        {{.CC}} {{.CC_FLAGS}} \
        lab.c \
        {{range .SOURCE_FILES}} {{.}} {{end}} \
        -fsanitize=address \
        -fno-omit-frame-pointer \
        -o {{.LAB_EXECUTABLE_NAME}}
    sources:
      - "*.c"
    generates:
      - "{{.LAB_EXECUTABLE_NAME}}"

  lab:run:
    deps:
      - lab:build
    cmds:
      - ./{{.LAB_EXECUTABLE_NAME}}

  lab:leaks:
    deps:
      - lab:build
    cmds:
      - cp /usr/local/lib/standardloop/libstandardloop-util.dylib ./ # to get around sips we need to move dylibs to local dir :(
      - leaks --atExit -- ./{{.LAB_EXECUTABLE_NAME}}
      - rm libstandardloop-util.dylib
