---
version: "3"

# silent: true

includes:
  c: https://raw.githubusercontent.com/standardloop/taskfiles/refs/heads/main/c.yml # can pin in future
  # c: ../taskfiles/c.yml

vars:
  SOURCE_FILES:
    - temp.c
    - stringhelpers.c
    - env.c
    - explode.c
    - regex.c
  TEST_SOURCE_FILES:
    - env.test.c
    - explode.test.c
    - stringhelpers.test.c
  DYLIB_NAME: libstandardloop-util.dylib
  DYLIB_HEADER: util.h
  # DYN_LIBS_USED: "-lstandardloop-util"

tasks:
  default:
    cmds:
      - task: test:build

  # GH_RELEASE_VERSION is set by CI
  release:
    # deps:
    #   - dependencies
    cmds:
      - task: c:release

  # dependencies:
  #   deps:
  #     - c:dependencies:util

  test:
    deps:
      - test:run

  test:build-sanitize:
    # deps:
    #   - dependencies
    cmds:
      - task: c:test:build-sanitize

  test:build:
    # deps:
    #   - dependencies
    cmds:
      - task: c:test:build

  test:run:
    deps:
      - test:build
    cmds:
      - ./{{.TEST_EXECUTABLE_NAME}}

  clean:
    deps:
      - c:test:clean

  fmt:
    deps:
      - c:fmt

  docs:
    deps:
      - c:docs:moxygen
